services:
  photo-analysis-server:
    build: .
    container_name: photo-analysis-server
    ports:
      - "9292:3000"
    environment:
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      PHOTO_ANALYSIS_URL: ${PHOTO_ANALYSIS_URL_PROD}
      CORS_ORIGINS: ${CORS_ORIGINS}
      DATABASE_PATH: /usr/src/app/data/db.sqlite
    volumes:
      - ./app-data:/usr/src/app/data
    restart: unless-stopped
